# Generated by Django 5.0.1 on 2025-01-30 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("customers_served", models.IntegerField()),
                ("average_service_time", models.DurationField()),
                ("service_rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "agent performance",
                "verbose_name_plural": "agent performances",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "wait_time_satisfaction",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "service_satisfaction",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "customer feedback",
                "verbose_name_plural": "customer feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueueMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("average_wait_time", models.DurationField()),
                ("total_customers", models.IntegerField()),
                ("served_customers", models.IntegerField()),
                ("abandoned_customers", models.IntegerField()),
                (
                    "peak_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TimeField(), size=None
                    ),
                ),
                (
                    "service_efficiency",
                    models.FloatField(help_text="Ratio of served to total customers"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "queue metrics",
                "verbose_name_plural": "queue metrics",
                "ordering": ["-date"],
            },
        ),
    ]
