# Generated by Django 5.0.1 on 2025-02-24 15:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_remove_organization_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("QP", "Queue Performance"),
                            ("AP", "Agent Performance"),
                            ("CS", "Customer Satisfaction"),
                            ("SU", "System Usage"),
                            ("CU", "Custom"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("PD", "PDF"),
                            ("EX", "Excel"),
                            ("CS", "CSV"),
                            ("HT", "HTML"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        help_text="Template file for custom reports",
                        null=True,
                        upload_to="report_templates/",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters required for the report"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "report template",
                "verbose_name_plural": "report templates",
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DA", "Daily"),
                            ("WE", "Weekly"),
                            ("MO", "Monthly"),
                            ("QU", "Quarterly"),
                            ("YE", "Yearly"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters for report generation"
                    ),
                ),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        help_text="Email addresses to receive the report",
                        size=None,
                    ),
                ),
                ("next_run", models.DateTimeField()),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reporting.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "scheduled report",
                "verbose_name_plural": "scheduled reports",
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters used for generation"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_reports/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("GE", "Generating"),
                            ("CO", "Completed"),
                            ("FA", "Failed"),
                        ],
                        default="PE",
                        max_length=2,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="reporting.reporttemplate",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="reporting.scheduledreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "generated report",
                "verbose_name_plural": "generated reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
