# Generated by Django 5.0.1 on 2025-02-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("EM", "Email"),
                            ("SM", "SMS"),
                            ("PU", "Push"),
                            ("WA", "WhatsApp"),
                            ("IA", "In-App"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(help_text="Channel specific configuration"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification channel",
                "verbose_name_plural": "notification channels",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("EM", "Email"),
                            ("SM", "SMS"),
                            ("PU", "Push"),
                            ("WA", "WhatsApp"),
                            ("IA", "In-App"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject for email notifications",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Template content with placeholders"),
                ),
                (
                    "html_content",
                    models.TextField(
                        blank=True, help_text="HTML content for email notifications"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification template",
                "verbose_name_plural": "notification templates",
                "unique_together": {("organization", "name", "template_type")},
            },
        ),
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "recipients_filter",
                    models.JSONField(help_text="Filter criteria for recipients"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Data for notification content"
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("SC", "Scheduled"),
                            ("SE", "Sending"),
                            ("ST", "Sent"),
                            ("DE", "Delivered"),
                            ("RE", "Read"),
                            ("FA", "Failed"),
                        ],
                        default="PE",
                        max_length=2,
                    ),
                ),
                ("total_count", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="notifications.notificationchannel",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification batch",
                "verbose_name_plural": "notification batches",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("EM", "Email"),
                            ("SM", "SMS"),
                            ("PU", "Push"),
                            ("WA", "WhatsApp"),
                            ("IA", "In-App"),
                        ],
                        max_length=2,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
                "unique_together": {("user", "channel_type")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("SC", "Scheduled"),
                            ("SE", "Sending"),
                            ("ST", "Sent"),
                            ("DE", "Delivered"),
                            ("RE", "Read"),
                            ("FA", "Failed"),
                        ],
                        default="PE",
                        max_length=2,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LO", "Low"),
                            ("NO", "Normal"),
                            ("HI", "High"),
                            ("UR", "Urgent"),
                        ],
                        default="NO",
                        max_length=2,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data for the notification",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="notifications.notificationchannel",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="notificatio_status_d8d933_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="notificatio_recipie_f39341_idx",
                    ),
                ],
            },
        ),
    ]
