# Generated by Django 5.0.1 on 2025-01-30 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = []
