# Generated by Django 5.0.1 on 2025-02-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("basic", "Basic"), ("premium", "Premium")],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="region",
            field=models.CharField(
                choices=[
                    ("north", "North"),
                    ("south", "South"),
                    ("east", "East"),
                    ("west", "West"),
                    ("central", "Central"),
                ],
                default="central",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("pending", "Pending"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
