# Generated by Django 5.0.1 on 2025-01-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20250130_1330"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconsent",
            name="granted",
            field=models.BooleanField(default=True, verbose_name="granted"),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="user_agent",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="user agent"
            ),
        ),
    ]
