# Generated by Django 5.0.1 on 2025-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_user_options_remove_user_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="securitykey",
            options={
                "verbose_name": "security key",
                "verbose_name_plural": "security keys",
            },
        ),
        migrations.RemoveField(
            model_name="securitykey",
            name="key_type",
        ),
        migrations.RemoveField(
            model_name="securitykey",
            name="last_used",
        ),
        migrations.RemoveField(
            model_name="securitykey",
            name="name",
        ),
        migrations.RemoveField(
            model_name="securitykey",
            name="sign_count",
        ),
        migrations.AddField(
            model_name="securitykey",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="securitykey",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="securitykey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="securitykey",
            name="key_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="securitykey",
            name="public_key",
            field=models.TextField(),
        ),
    ]
