# Generated by Django 5.0.1 on 2025-02-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ARContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("TX", "Text"),
                            ("IM", "Image"),
                            ("VD", "Video"),
                            ("3D", "3D Model"),
                            ("AN", "Animation"),
                        ],
                        max_length=2,
                    ),
                ),
                ("content", models.FileField(upload_to="ar/contents/")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("scale_x", models.FloatField(default=1.0)),
                ("scale_y", models.FloatField(default=1.0)),
                ("scale_z", models.FloatField(default=1.0)),
                ("rotation_x", models.FloatField(default=0.0)),
                ("rotation_y", models.FloatField(default=0.0)),
                ("rotation_z", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AR content",
                "verbose_name_plural": "AR contents",
            },
        ),
        migrations.CreateModel(
            name="ARMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("marker_image", models.ImageField(upload_to="ar/markers/")),
                (
                    "marker_data",
                    models.JSONField(help_text="AR marker recognition data"),
                ),
                (
                    "location_x",
                    models.FloatField(help_text="X coordinate in the venue"),
                ),
                (
                    "location_y",
                    models.FloatField(help_text="Y coordinate in the venue"),
                ),
                (
                    "location_z",
                    models.FloatField(help_text="Z coordinate in the venue"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AR marker",
                "verbose_name_plural": "AR markers",
            },
        ),
        migrations.CreateModel(
            name="NavigationPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_points",
                    models.JSONField(help_text="List of coordinates forming the path"),
                ),
                ("distance", models.FloatField(help_text="Path length in meters")),
                (
                    "estimated_time",
                    models.DurationField(help_text="Estimated walking time"),
                ),
                (
                    "is_accessible",
                    models.BooleanField(
                        default=True, help_text="Wheelchair accessible"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "navigation path",
                "verbose_name_plural": "navigation paths",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("floor_plan", models.ImageField(upload_to="ar/floor_plans/")),
                ("width", models.FloatField(help_text="Venue width in meters")),
                ("length", models.FloatField(help_text="Venue length in meters")),
                ("height", models.FloatField(help_text="Venue height in meters")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "venue",
                "verbose_name_plural": "venues",
            },
        ),
    ]
