# Generated by Django 5.0.1 on 2025-02-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("geolocation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(default="fr", max_length=10)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("location_tracking", models.BooleanField(default=True)),
                ("background_refresh", models.BooleanField(default=True)),
                ("offline_mode", models.BooleanField(default=False)),
                (
                    "default_vehicle",
                    models.JSONField(
                        blank=True, help_text="Default vehicle information", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favorite_branches",
                    models.ManyToManyField(
                        related_name="favorited_by", to="core.organizationbranch"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "app preference",
                "verbose_name_plural": "app preferences",
            },
        ),
        migrations.CreateModel(
            name="MobileDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique device identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("AN", "Android"), ("IO", "iOS"), ("HU", "Huawei")],
                        max_length=2,
                    ),
                ),
                ("device_name", models.CharField(max_length=255)),
                ("device_model", models.CharField(max_length=255)),
                ("os_version", models.CharField(max_length=50)),
                ("app_version", models.CharField(max_length=50)),
                (
                    "push_token",
                    models.CharField(
                        blank=True, help_text="Push notification token", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("IN", "Inactive"),
                            ("BL", "Blocked"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="geolocation.userlocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "mobile device",
                "verbose_name_plural": "mobile devices",
            },
        ),
        migrations.CreateModel(
            name="AppFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("BU", "Bug Report"),
                            ("FE", "Feature Request"),
                            ("IM", "Improvement"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="feedback/screenshots/"
                    ),
                ),
                ("app_version", models.CharField(max_length=50)),
                (
                    "device_info",
                    models.JSONField(
                        help_text="Device information when feedback was submitted"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="mobile.mobiledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "app feedback",
                "verbose_name_plural": "app feedback",
            },
        ),
        migrations.CreateModel(
            name="MobileSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mobile.mobiledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "mobile session",
                "verbose_name_plural": "mobile sessions",
            },
        ),
        migrations.CreateModel(
            name="OfflineData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("QU", "Queue"),
                            ("TI", "Ticket"),
                            ("BR", "Branch"),
                            ("MA", "Map"),
                        ],
                        max_length=2,
                    ),
                ),
                ("data", models.JSONField()),
                ("version", models.IntegerField(default=1)),
                (
                    "is_dirty",
                    models.BooleanField(
                        default=False, help_text="Indicates if data needs to be synced"
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_data",
                        to="mobile.mobiledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "offline data",
                "verbose_name_plural": "offline data",
                "unique_together": {("device", "data_type")},
            },
        ),
    ]
